### ISSUE TITLE
Tracks skip randomly

### ISSUE THREAD

**Issue by mazkolain-zz** [mazkolain-zz/spotimc#10]
Probably related to the fact that XBMC opens many threads per track, and the buffer validation mechanism used. It should be less strict.

**Comment by varazir** [comment]
Don't know if it's the same, but spotimc change track before it's done

**Comment by mazkolain-zz** [comment]
Yes it's probably the same. It goes to the next track in the middle (well, anywhere on the current track's progress) of the current one.

**Comment by mazkolain-zz** [comment]
It was related to threads, but not XBMC's fault. It was a race condition on the proxy module that killed streams randomly.
