### ISSUE TITLE
Rasbmc Can't get back into Spotimc UI after viewing other screens

### ISSUE THREAD

**Issue by monquixote** [mazkolain-zz/spotimc#100]
Hi first of all awesome plug-in fantastic work it's really made my day that this works so nicely on the Pi. 

I've been using the plugin with Raspbmc (substituting in the hard float libspotify) and it works really well however I have found that if I leave the spotimc menu and look at other menus in xbmc when I try and get back into spotimc it won't let me back in and then shortly after the playback fails. 
After this I have to reboot to get it working again.

**Comment by mazkolain-zz** [comment]
Hello,

First of all congratulations for filing issue #100! Sadly this one has been widely asked before like on #28, so I'm marking this as duplicate.

I have to say that I have plans to implement this on future releases, but unfortunately requires considerable amounts of head-scratching, so it cannot be accomplished in the short term. Anyway, thanks for the feedback!

**Comment by monquixote** [comment]
Cheers for replying. 

I did have a quick look, but didn't spot the duplicate, thanks for pointing it out. 
Been listening to Spotify all day on my Pi, cheers again for your excellent work!
