### ISSUE TITLE
download option

### ISSUE THREAD

**Issue by sstrigler** [mazkolain-zz/spotimc#101]
Hej, as github removed the possibility to upload files for download there are no 'releases' of spotimc available anymore. Maybe this could be fixed by tagging master when appropriate? Or find some other location where to put downloadable files.

**Comment by sstrigler** [comment]
also a short guide on how to create your own release would be nice. seems like when just doing "python build.py" there are all the dependencies missing from within the created zip file

**Comment by mazkolain-zz** [comment]
Hello,

It's true that Github deprecated downloads some time ago, but the uploaded files page is still functional (albeit somewhat hidden):
https://github.com/mazkolain/spotimc/wiki/Downloads

Also, there is a guide available that explains how to set up a running installation of Spotimc from sources:
https://github.com/mazkolain/spotimc/wiki/Spotimc-Development

Anyway, thanks for the feedback. Perhaps I should make the download page more visible, linking it on the readme...

**Comment by mazkolain-zz** [comment]
Hello,

I've just updated the readme adding a link to the download page:
https://github.com/mazkolain/spotimc/blob/master/README.md
