### ISSUE TITLE
Spotimc Stopped working in Raspbmc

### ISSUE THREAD

**Issue by monquixote** [mazkolain-zz/spotimc#102]
SpotiMC was working on my Raspbmc perfectly, but since I did an update of XBMC it stopped working. 

The log message I get when I try and play anything is this:

21:39:54 T:2046800960  NOTICE: 192.168.1.72 - - [28/Mar/2013:21:39:54] "GET /track/6hzUhWGMBWKntf3kcv0oGu.wav?idx=7 HTTP/1.1" 416 - "" "Spotimc/1.0-beta3 (XBMC/12.1 Git:20130317-0d373cc)"
21:39:54 T:2046800960  NOTICE: .
21:39:54 T:2030023744 WARNING: FillBuffer: curl failed with code 22
21:39:54 T:2030023744   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
21:39:54 T:2030023744   ERROR: Open - failed to open source http://192.168.1.72:8080/track/6hzUhWGMBWKntf3kcv0oGu.wav?idx=7|X-Spotify-Token=2c9d69133527d0c895dd509c3a24bfe79025e716&User-Agent=Spotimc%2F1.0-beta3+%28XBMC%2F12.1+Git%3A20130317-0d373cc%29
21:39:54 T:2030023744   ERROR: COMXPlayer::OpenInputStream - error opening [http://192.168.1.72:8080/track/6hzUhWGMBWKntf3kcv0oGu.wav?idx=7|X-Spotify-Token=2c9d69133527d0c895dd509c3a24bfe79025e716&User-Agent=Spotimc%2F1.0-beta3+%28XBMC%2F12.1+Git%3A20130317-0d373cc%29]
21:39:54 T:2030023744  NOTICE: COMXPlayer::OnExit()
21:39:54 T:2030023744  NOTICE: COMXPlayer::OnExit() deleting input stream
21:39:54 T:3038175232   ERROR: Playlist Player: skipping unplayable item: 7, path [http://192.168.1.72:8080/track/6hzUhWGMBWKntf3kcv0oGu.wav?idx=7|X-Spotify-Token=2c9d69133527d0c895dd509c3a24bfe79025e716&User-Agent=Spotimc%2F1.0-beta3+%28XBMC%2F12.1+Git%3A20130317-0d373cc%29]
21:39:54 T:3038175232  NOTICE: OMXClock using video as reference

**Comment by mazkolain-zz** [comment]
Hello,

This issue was reported in #98 and it's already fixed. The fix will be included on the next release, which is near the corner.

It was mistakenly reported to affect Openelec only, but I've just updated it to reflect that it affected XBMC 12.1.

Regards,

Mikel

**Comment by misa2610** [comment]
1) Download the compiled egg here: http://up.kibje.com/20130328/PyspotifyCtypesProxy.egg
2) Put the file you downloaded here: %APPDATA%\XBMC\addons\script.audio.spotimc\resources\libs\ overwriting the file that was present.
3) Restart XBMC

This worked perfect on OE 3.0.0 and 12.1

**Comment by monquixote** [comment]
Brilliant 

I'll try that and see if it works.

**Comment by yorugua** [comment]
Thanks, works perfectly.
