### ISSUE TITLE
Fix focus on albums/Singles with just one track

### ISSUE THREAD

**Issue by newphreak** [mazkolain-zz/spotimc#103]
Can we make it select the track, instead of the top menu on albums/singles with just one track? currently on those it goes to the top menu, while albums with more then one track selects the first track when you enter it.

This should be an easy fix.

**Comment by mazkolain-zz** [comment]
Tested, and it happens also from time to time on albums with more than one track, so it could be related to some kind of race condition. Adding proper synchronization the fix should be easy as suggested.

Thanks for reporting!
