### ISSUE TITLE
Beta-4 // Start failed (skinutils not found?!)

### ISSUE THREAD

**Issue by chrstnwhlrt** [mazkolain-zz/spotimc#104]
I updated spotimc on xbmc 12.1 (team xbmc-stable ppa) from beta3 to beta4 and now the plugin doesn't start anymore, it claims not finding "skinutils".

17:42:27 T:139979816847232   ERROR: Texture manager unable to load file: /home/christian/tmp/addons/spotimc-1.0-beta4.zip/icon.png
17:42:27 T:139978621318912  NOTICE: Thread Background Loader start, auto delete: false
17:42:37 T:139978621318912  NOTICE: Previous line repeats 2 times.
17:42:37 T:139978621318912  NOTICE: Thread XBPyThread start, auto delete: false
17:42:37 T:139978621318912  NOTICE: -->Python Interpreter Initialized<--
17:42:41 T:139978621318912   ERROR: Traceback (most recent call last):
17:42:41 T:139978621318912   ERROR:   File "/home/christian/.xbmc/addons/spotimc-1.0-beta4/default.py", line 52, in <module>
17:42:41 T:139978621318912   ERROR:     from skinutils import reload_skin
17:42:41 T:139978621318912   ERROR: ImportError: No module named skinutils
17:42:41 T:139978621318912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: name 'unload_library' is not defined
                                            Traceback (most recent call last):
                                              File "/home/christian/.xbmc/addons/spotimc-1.0-beta4/default.py", line 95, in <module>
                                                unload_library("libspotify")
                                            NameError: name 'unload_library' is not defined
                                            -->End of Python script error report<--
17:42:42 T:139978576889600  NOTICE: Thread Background Loader start, auto delete: false
17:42:42 T:139979816847232  NOTICE: Previous line repeats 1 times.
17:42:42 T:139979816847232   ERROR: ClearBlock: Trying to clear non existent block /home/christian/.xbmc/addons/spotimc-1.0-beta4

**Comment by chrstnwhlrt** [comment]
..could be my fault, as the "tags" are not longer to be used as "downloads" (see issue "download option")
therefore there are some binaries maybe missing within.. correct?

**Comment by mazkolain-zz** [comment]
Hello,

The tags never had been able to provide valid download packages, since as said, they do not include some required binary dependencies (libspotify dll's and some python libs).

I've updated the readme and it now clearly displays a link to the download page:
https://github.com/mazkolain/spotimc/blob/master/README.md

Regards,

Mikel
