### ISSUE TITLE
Can't install zip file due to Failed write to special://[...]/libspotify.so

### ISSUE THREAD

**Issue by excudo** [mazkolain-zz/spotimc#109]
I have the same issue as this guy: https://github.com/mazkolain/spotimc/issues/87

It is the first time i tried to install the spotimc plugin and i get this error when i try to install it from the zip file i just downloaded:

09:58:31 T:140277138298624   ERROR: Cache - Failed write to file special://home/addons/script.audio.spotimc/resources/dlls/linux/armv6hf/libspotify.so

I'm running openelec XMBC 12.0-RC3

**Comment by mazkolain-zz** [comment]
Hello @excudo, sorry for the delayed answer.

The error report on the linked issue gives more details on the next line:

> ERROR: Could not read addon description of script.audio.spotimc

Is that also your case? Anyway, try sending a pastebin of a full log file, and hopefully even more details will show up there.

**Comment by excudo** [comment]
Ok, i feel a bit silly.
As i was tailing the log file it suddenly occured to me that i should do a check on the available disk space. As it turned out, my ArtistSlideshow plugin had grown to 3GB of cached images and had used up all the available diskspace. Once i deleted the cache-folder spotimc installed just fine :-)

Thanks for the reply and the good work you're doing!

**Comment by mazkolain-zz** [comment]
Good to hear that you solved your issue :) I was starting to think that the download page was serving corrupt files (since it changed recently).

Thanks for the update!
