### ISSUE TITLE
When looking for lyrics, music mutes

### ISSUE THREAD

**Issue by che1404** [mazkolain-zz/spotimc#110]
Hi!

We are experiencing the following problem with Spotimc 1.0 beta4 and XBMC Frodo. When we use the Lyrics script (CU LRC Lyrics) the music is muted. Playback continues, but the music mutes.

Any idea on what could be happening?

Thanks in advance,
Robert.

**Comment by che1404** [comment]
By the way, the OS is Ubuntu 12.10, for x64 architecture.

**Comment by mazkolain-zz** [comment]
Hello,

This is a known issue, and needs changes on both Spotimc's and the lyrics script's side. I'll have to talk with the lyrics script developer to find a possible solution.

In the meantime, you can check this link for a possible solution:
https://github.com/mazkolain/spotimc/issues/92#issuecomment-15029166

**Comment by mazkolain-zz** [comment]
Hi,

The fix is already present on beta5, plus the required changes for cu.lrclyrics.

Closing this issue.
