### ISSUE TITLE
Spotimc Crashes randomly

### ISSUE THREAD

**Issue by keydon** [mazkolain-zz/spotimc#111]
Hi,

Spotimc crashes every now and then, there is no regularity i can see.
So here is the xbmc.log with the the last 6 min before the crash.

http://pastebin.com/2pqdBaJZ

Seems to be buffer related. Maybe you can catch the error and then just skip the track or something :)

Thank you very much!
keydon

**Comment by mazkolain-zz** [comment]
Hello @keydon,

Are you using a lyrics provider script? There are known issues between Spotimc and them on some specific situations, with various results: Tracks get skipped or even Spotimc crashes XBMC.

Regards,

**Comment by mazkolain-zz** [comment]
Hi,

This was probably related to some buffer cancellation issues when crossfade was enabled (on Linux).

This will be fixed by the next beta build which is going to be released soon.

Regards,

Mikel
