### ISSUE TITLE
Creating skins

### ISSUE THREAD

**Issue by standaniels** [mazkolain-zz/spotimc#112]
I would like to create a skin for Spotimc. Where do I begin? Can I read somewhere how skins are built?

**Comment by mazkolain-zz** [comment]
Hello @standaniels,

Spotimc's skin resides on the resources/skins/DefaultSkin folder, like on other addons providing a custom UI.

The following link of the XBMC wiki explains every aspect of XBMC's skinning engine (structure, controls, ...):
http://wiki.xbmc.org/index.php?title=Skinning

It explains in detail how to build a new skin for XBMC (a full featured skin for every window, dialog and so on), but most of the information there should be valid also for addon specific skins.

Regards,
