### ISSUE TITLE
Spotimc change song every 55 seconds

### ISSUE THREAD

**Issue by javipod** [mazkolain-zz/spotimc#113]
Hi

I'm using raspberry pi xbmc last update and spotimc addon I have that all songs only plays 55 seconds, after that next song begins to play. I have checking the configuration and all seems good. That happens from last update of xmbc. Is there any configuration item that need change?

Thank you very much

**Comment by mazkolain-zz** [comment]
Hello @javipod,

Could you please provide a pastebin of a log file with the details of this issue?

I've been using Spotimc on the pi for a while (through Raspbmc) and didn't ever noticed this issue. It could be related to some additional script you are using alongside Spotimc (lyric providers, fanart loaders, etc.), or even a new unseen bug on Spotimc's side.

Thanks in advance,

**Comment by javipod** [comment]
Hello @mazkolain 

First of all thank you for your reply. Here you have the log of three songs changing every 55 seconds. I've got installed some video plugins for TV channels and one for radio.

Hope that helps you

pi@raspbmc:/var/log$ tail -f  xbmc.log
20:01:20 T:2713711680  NOTICE: 127.0.0.1 - - [21/May/2013:20:01:20] "GET /track/2prHJSKJ7HLimNmZonIVMe.wav?idx=1 HTTP/1.1" 200 32634044 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:20130502-32b1a5e)"
20:01:20 T:2713711680  NOTICE: .
20:01:20 T:2652222528  NOTICE: Creating Demuxer
20:01:20 T:2585113664  NOTICE: Thread CFileCache start, auto delete: false
20:01:22 T:2652222528  NOTICE: Opening audio stream: 0 source: 256
20:01:22 T:2652222528  NOTICE: Creating audio thread
20:01:22 T:2913723456  NOTICE: Thread COMXPlayerAudio start, auto delete: false
20:01:22 T:2652222528 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
20:01:22 T:2913723456 WARNING: Previous line repeats 1 times.
20:01:22 T:2913723456  NOTICE: OMXClock using audio as reference
20:01:59 T:2585113664   ERROR: WriteToCache - failed to write to file. err: 28
20:01:59 T:2585113664   ERROR: CFileCache::Process - error writing to cache
20:02:18 T:2652222528  NOTICE: COMXPlayer::OnExit()
20:02:18 T:2652222528  NOTICE: OMXPlayer: eof, waiting for queues to empty
20:02:18 T:2652222528  NOTICE: OMXPlayer: closing audio stream
20:02:18 T:2652222528  NOTICE: Closing audio stream
20:02:18 T:2652222528  NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty
20:02:18 T:2913723456  NOTICE: thread end: OMXPlayerAudio::OnExit()
20:02:18 T:2652222528  NOTICE: OMXClock using video as reference
20:02:18 T:2652222528  NOTICE: COMXPlayer::OnExit() deleting demuxer
20:02:18 T:2652222528  NOTICE: COMXPlayer::OnExit() deleting input stream
20:02:18 T:2688545856  NOTICE: 127.0.0.1 - - [21/May/2013:20:02:18] "HEAD /track/4FAkQBP5QdKnpdQuNKLVjH.wav?idx=2 HTTP/1.1" 200 40924844 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:20130502-32b1a5e)"
20:02:18 T:2688545856  NOTICE: .
20:02:18 T:3037810688  NOTICE: COMXPlayer: Opening: http://127.0.0.1:8080/track/4FAkQBP5QdKnpdQuNKLVjH.wav?idx=2|X-Spotify-Token=139281170ad27b0c020249da1e24c39a41e7834c&User-Agent=Spotimc%2F1.0-beta4+%28XBMC%2F12.2+Git%3A20130502-32b1a5e%29
20:02:18 T:2652222528  NOTICE: Thread COMXPlayer start, auto delete: false
20:02:18 T:2652222528  NOTICE: Creating InputStream
20:02:18 T:2913723456  NOTICE: Thread Jobworker start, auto delete: true
20:02:18 T:2775315520  NOTICE: libspotify log: 18:02:18.731 I [social_presence.cpp:135] Presence: A track was played
20:02:19 T:2747266112  NOTICE: 127.0.0.1 - - [21/May/2013:20:02:19] "GET /track/4FAkQBP5QdKnpdQuNKLVjH.wav?idx=2 HTTP/1.1" 200 40924844 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:20130502-32b1a5e)"
20:02:19 T:2747266112  NOTICE: .
20:02:19 T:2652222528  NOTICE: Creating Demuxer
20:02:19 T:2585113664  NOTICE: Thread CFileCache start, auto delete: false
20:02:21 T:2652222528  NOTICE: Opening audio stream: 0 source: 256
20:02:21 T:2652222528  NOTICE: Creating audio thread
20:02:21 T:2551559232  NOTICE: Thread COMXPlayerAudio start, auto delete: false
20:02:21 T:2652222528 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
20:02:21 T:2551559232 WARNING: Previous line repeats 1 times.
20:02:21 T:2551559232  NOTICE: OMXClock using audio as reference
20:02:54 T:2585113664   ERROR: WriteToCache - failed to write to file. err: 28
20:02:54 T:2585113664   ERROR: CFileCache::Process - error writing to cache
20:03:17 T:2652222528  NOTICE: COMXPlayer::OnExit()
20:03:17 T:2652222528  NOTICE: OMXPlayer: eof, waiting for queues to empty
20:03:17 T:2652222528  NOTICE: OMXPlayer: closing audio stream
20:03:17 T:2652222528  NOTICE: Closing audio stream
20:03:17 T:2652222528  NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty
20:03:17 T:2551559232  NOTICE: thread end: OMXPlayerAudio::OnExit()
20:03:17 T:2652222528  NOTICE: OMXClock using video as reference
20:03:17 T:2652222528  NOTICE: COMXPlayer::OnExit() deleting demuxer
20:03:17 T:2652222528  NOTICE: COMXPlayer::OnExit() deleting input stream
20:03:17 T:2671768640  NOTICE: 127.0.0.1 - - [21/May/2013:20:03:17] "HEAD /track/1LRdQdgthyaW7z97jYnbHt.wav?idx=3 HTTP/1.1" 200 39337244 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:20130502-32b1a5e)"
20:03:17 T:2671768640  NOTICE: .
20:03:17 T:3037810688  NOTICE: COMXPlayer: Opening: http://127.0.0.1:8080/track/1LRdQdgthyaW7z97jYnbHt.wav?idx=3|X-Spotify-Token=139281170ad27b0c020249da1e24c39a41e7834c&User-Agent=Spotimc%2F1.0-beta4+%28XBMC%2F12.2+Git%3A20130502-32b1a5e%29
20:03:17 T:2652222528  NOTICE: Thread COMXPlayer start, auto delete: false
20:03:17 T:2652222528  NOTICE: Creating InputStream
20:03:17 T:2551559232  NOTICE: Thread Jobworker start, auto delete: true
20:03:17 T:2775315520  NOTICE: libspotify log: 18:03:17.944 I [social_presence.cpp:135] Presence: A track was played
20:03:19 T:2730488896  NOTICE: 127.0.0.1 - - [21/May/2013:20:03:19] "GET /track/1LRdQdgthyaW7z97jYnbHt.wav?idx=3 HTTP/1.1" 200 39337244 "" "Spotimc/1.0-beta4 (XBMC/12.2 Git:20130502-32b1a5e)"
20:03:19 T:2730488896  NOTICE: .
20:03:19 T:2652222528  NOTICE: Creating Demuxer
20:03:19 T:2585113664  NOTICE: Thread CFileCache start, auto delete: false
20:03:20 T:2652222528  NOTICE: Opening audio stream: 0 source: 256
20:03:20 T:2652222528  NOTICE: Creating audio thread
20:03:20 T:2913723456  NOTICE: Thread COMXPlayerAudio start, auto delete: false
20:03:20 T:2652222528 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
20:03:20 T:2913723456 WARNING: Previous line repeats 1 times.
20:03:20 T:2913723456  NOTICE: OMXClock using audio as reference

Thank you very much!!!

**Comment by javipod** [comment]
Hola Mikel

Díria que con ese nombre tienes que ser Vasco. Yo soy Catalán. Si no tienes inconveniente podemos escribir en castellano. De lo contrario dímelo que no hay problema. Por cierto he deshabilitado todos los plugins y continuo teniendo el mismo problema.

Muchas gracias de antemano :)

**Comment by mazkolain-zz** [comment]
Hola Javi,

Pues sí, has acertado. ¿Tanto se nota? :)

Tal y como comentas estaría bien poder hablar en castellano, aunque me temo que impediría a otros seguir el hilo de la incidencia, de modo que si tampoco hay problemas por tu parte preferiría continuar en inglés.

**Possible cause:**
Reading the log file you provided, I can clearly see several traces of the following error:

> 20:01:59 T:2585113664 ERROR: WriteToCache - failed to write to file. err: 28

Which in turn could possibly explain where the issue comes from (errno 28, no space left on the device):
http://www.virtsync.com/c-error-codes-include-errno

Also, Spotimc relies on wav streams (encapsulating the raw PCM data delivered by libspotify), so I would expect hitting this issue often when the available space is low. I would try to keep free space above 500M in order to get away from these kind of issues.

**Comment by javipod** [comment]
Hello Mikel

It has been solved reinstalling raspbmc and spotimc add-on. All works perfect now!!! 

Thank you very much for your help!!!

Javi
