### ISSUE TITLE
Songs don't start on XBMC 12.2

### ISSUE THREAD

**Issue by mjamin** [mazkolain-zz/spotimc#115]
Songs are stuck at 0:00 and don't start playing, everything else seems to work just fine. Can someone confirm?

**Comment by mazkolain-zz** [comment]
Spotimc works well on XBMC 12.2 under Windows, OSX and Linux. Could you please provide a pastebin of the log file you get when this happens?

Also, Spotimc uses an embedded http proxy to serve images and track streams to XBMC. If you are also unable to see the album covers I would check if firewall software is blocking connections to this proxy server.

**Comment by mjamin** [comment]
It was some other issue (switching from HDMI to Optical output fixed it).
