### ISSUE TITLE
Spotimc with Artist slideshow question

### ISSUE THREAD

**Issue by lanfr0t** [mazkolain-zz/spotimc#126]
I wondered if anyone is using Spotimc with the artist slideshow add-on.  I used to use this on Eden/Transparency skin/Spotimc without any issues.  Since updating to Frodo and the latest spotimc, I can usually get through the first song, then a few seconds into the second song, play back pauses for a bit, then continues, then pauses (repeating cycle).  Eventually, playback will move to the next song in the queue without finishing the current song, and repeat the pause, unpause behavior continuing through the queue this way.  Has anyone else seen this issue?  I've tried this on 3 different xbmc machines in the house.

Thanks for any feedback.

**Comment by mazkolain-zz** [comment]
Hello,

This is a known issue and I'm actively investigating it. I have some clues of what could be going on, but don't have a fix yet.

As a temporary workaround you can disable the Artist Slideshow plugin, but you'll lose all the functionality it provides.

**Comment by mazkolain-zz** [comment]
Hi,

The pause/unpause behavior was caused due to thread locking issues on the JSON api. This should be fixed on the latest alpha builds of XBMC Gotham.

Regards,

Mikel
