### ISSUE TITLE
No sound on next item in playlist sometimes

### ISSUE THREAD

**Issue by johnnyleitrim** [mazkolain-zz/spotimc#135]
If I'm listening to an album or a playlist, sometimes when it advanced to the next song there is no sound, even though I can see the progress bar and timer moving forward as normal.  I have to go to the next or previous song in the playlist, and then back to the tune to get it to play.

This does not always happen, but happens frequently - maybe 3/4 times in a 12 song album.

**Comment by mazkolain-zz** [comment]
Hi,

From the description seems related to issue #127, which was closed recently but the fix it's not included yet on the latest stable release.

I'm planning to make a new release in a matter of days so the fix will be available soon. Stay tuned!

Thanks for reporting!
