### ISSUE TITLE
CULyrics = no audio

### ISSUE THREAD

**Issue by newphreak** [mazkolain-zz/spotimc#138]
It seems that culyrics lookup kills the audiostream. I do not use this add-on, think it was left enabled by some skin i tested earlier. Anyhow, with this enabled, as soon as you go to fullscreen visualisation and culyrics starts to search for lyrics the music stream dies.

**Comment by newphreak** [comment]
ups, duplicate, didn't look closely enough. #110

**Comment by mazkolain-zz** [comment]
As suggested on #110, it requires changes on both cu.lrclyrics and Spotimc. The required PR is already merged on the cu.lrclyrics addon, and the next Spotimc release (which should see light soon) will include the fix for this.

Thanks for reporting!

**Comment by satrich** [comment]
I still have the issue that audio breaks after cu.lrclyrics has searched for lyrics.
I am using the Aeon skin in XBMC on Windows 8.1. Using your latest Beta 5.

Anyway, you created a great Add-on. It is very much appreciated.

**Comment by mazkolain-zz** [comment]
Hi,

As stated above, the required change on the lyrics script is already merged, but the latest release of it does not yet include this patch.

You'll have to try with the usual workaround in the meantime:
https://github.com/mazkolain/spotimc/issues/92#issuecomment-15029166

**Comment by satrich** [comment]
OK. Thanks for your answer. I figured that out myself. But in the changelog it is saying that is is fixed. So, I just thought to mention it here that it is not fixed.

**Comment by mazkolain-zz** [comment]
Hi @satrich,

Is true that the changelog may be quite misleading on this issue. Perhaps I should update the faq, or even better: Ask the lyrics plugin author if a snapshot release is possible...
