### ISSUE TITLE
"Premium account required" even if the account IS premium

### ISSUE THREAD

**Issue by nikkow** [mazkolain-zz/spotimc#142]
Hi,

I spotted a bug on SpotiMC v.1.0-beta4 (running on a MAC with XBMC Frodo). During the login process, I log in with my account and I get the error "A premium account is required". I subscribed a premium account earlier this month (and I am still in the 30-days free period). 

Best,
N.

**Comment by mazkolain-zz** [comment]
Hi @nikkow,

Did the credentials of your account work in the past with Spotimc? Or it's the first time you are attempting to log in?

Also note that any paid account type won't work with Spotimc (it's the case of Unlimited accounts), as the underlying libspotify library limits this.

**Comment by nikkow** [comment]
Hi @mazkolain,

This is a brand-new installation, I've never logged in before. However, I seemed to have 2 different accounts on spotify (one free and one premium), hence the mistake: I was using the free account to login. 

Thing is, the premium account is using a Facebook session. Is there a way to login using FB on Spotimc?

Best,
N.

**Comment by mazkolain-zz** [comment]
You should be able to login with Facebook using your (Facebook) email address and password pair.

Regards,

Mikel

**Comment by nikkow** [comment]
Indeed, that worked. Thanks for your help. :-)

**Comment by mazkolain-zz** [comment]
You're welcome!

**Comment by eusi** [comment]
Hey!

Same problem here, with the difference that I already tried fb-email + fb-pw. Wont work: "A premium account is required"

Fresh installation SpotiMC v.1.0-beta4 on openelec 3.24 (xmbc 12.2 frodo, Raspberry Pi).
I am using Spotify "Unlimited" for about one year.

regards
eusi

**Comment by mazkolain-zz** [comment]
As stated on my previous answer, keep in mind that unlimited accounts won't work with Spotimc, only premium accounts are allowed by the underlying libspotify library.

**Comment by eusi** [comment]
Whoops i guess i missed this note. Sry :/ And thanks for your answer!

Do you think that your SpotiMC (or this libspotify library) is able to also run for unlimited (spotify) accounts in near future?

**Comment by mazkolain-zz** [comment]
@eusi: This really depends on the closed source libspotify library, and consequently on it's owner: Spotify.

They recently enabled free acounds on their mobile app (ad driven), so we may (or may not) see some movements regarding third party apps like Spotimc. Who knows...

**Comment by eusi** [comment]
Ok. Thanks a lot for your (very fast) help!!
