### ISSUE TITLE
Spotimc beta4 not starting in later xbmc 13 nightlies (Gotham)

### ISSUE THREAD

**Issue by olehj** [mazkolain-zz/spotimc#144]
Spotimc beta4 does not start with newer xbmc nightlies (gotham), it's showing the loading screen and crashes at the end, usually faster to just reboot the box.

From xbmc.log:

01:15:25 T:1970273088  NOTICE: -->Python Interpreter Initialized<--
01:15:25 T:1880943424  NOTICE: -->Python Interpreter Initialized<--
01:15:27 T:1880943424  NOTICE: /home/xbmc/.xbmc/addons/skin.confluence/write_test.txt
01:16:07 T:1970273088  NOTICE: /home/xbmc/.xbmc/addons/skin.confluence/write_test.txt
01:16:07 T:1880943424   ERROR: /home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/XbmcSkinUtils.egg/skinutils/fonts.py:140: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
01:16:16 T:1880943424   ERROR: Previous line repeats 1 times.
01:16:16 T:1880943424  NOTICE: /home/xbmc/.xbmc/addons/skin.confluence/write_test.txt
01:16:16 T:1880943424  NOTICE: install include: /home/xbmc/.xbmc/addons/script.audio.spotimc/resources/skins/DefaultSkin/720p/includes.xml
01:16:17 T:1970273088  NOTICE: /home/xbmc/.xbmc/addons/skin.confluence/write_test.txt
01:16:24 T:1970273088  NOTICE: install include: /home/xbmc/.xbmc/addons/script.audio.spotimc/resources/skins/DefaultSkin/720p/includes.xml
01:16:50 T:1970273088   ERROR: Traceback (most recent call last):
01:16:50 T:1970273088   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/default.py", line 71, in <module>
01:16:50 T:1970273088   ERROR:     im.install_file(include_path)
01:16:50 T:1970273088   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/XbmcSkinUtils.egg/skinutils/includes.py", line 79, in install_file
01:16:51 T:1970273088   ERROR:     self.add_include(name, item)
01:16:51 T:1970273088   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/XbmcSkinUtils.egg/skinutils/includes.py", line 60, in add_include
01:16:51 T:1970273088   ERROR:     doc = self.**doc_cache.read(file)
01:16:51 T:1970273088   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/XbmcSkinUtils.egg/skinutils/__init**.py", line 330, in read
01:16:52 T:1970273088   ERROR:     self.**cached_docs[file] = ET.parse(file)
01:16:52 T:1970273088   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
01:16:55 T:1970273088   ERROR:     tree.parse(source, parser)
01:16:55 T:1970273088   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 657, in parse
01:16:56 T:1970273088   ERROR:     self._root = parser.close()
01:16:56 T:1970273088   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
01:16:56 T:1970273088   ERROR:     self._raiseerror(v)
01:16:56 T:1970273088   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
01:16:56 T:1970273088   ERROR:     raise err
01:16:56 T:1970273088   ERROR: ParseError: no element found: line 1, column 0
01:16:56 T:3002718016 WARNING: Cleanup: Having to cleanup texture button-nofocus.png
01:16:56 T:3002718016 WARNING: Cleanup: Having to cleanup texture button-focus.png
01:16:56 T:3002718016 WARNING: Skin has invalid include: dialogeffect
01:16:56 T:3002718016 WARNING: Skin has invalid include: VisibleFadeEffect
01:16:56 T:3002718016 WARNING: Skin has invalid include: CommonBackground
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeRecentlyAddedInfo
01:16:56 T:3002718016 WARNING: Skin has invalid include: Clock
01:16:56 T:3002718016 WARNING: Skin has invalid include: VisibleFadeEffect
01:16:56 T:3002718016 WARNING: Skin has invalid include: Window_OpenClose_Animation
01:16:56 T:3002718016 WARNING: Skin has invalid include: VisibleFadeEffect
01:16:56 T:3002718016 WARNING: Skin has invalid include: Window_OpenClose_Animation
01:16:56 T:3002718016 WARNING: Skin has invalid include: VisibleFadeEffect
01:16:56 T:3002718016 WARNING: Skin has invalid include: Window_OpenClose_Animation
01:16:56 T:3002718016 WARNING: Skin has invalid include: VisibleFadeEffect
01:16:56 T:3002718016 WARNING: Skin has invalid include: Window_OpenClose_Animation
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuCommonValues
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuVideos
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuCommonValues
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuMovies
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuCommonValues
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuTVShows
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuCommonValues
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuMusic
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuCommonValues
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuSystem
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuCommonValues
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuPlayDisc
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuCommonValues
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuLiveTV
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuCommonValues
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeSubMenuPictures
01:16:56 T:3002718016 WARNING: Skin has invalid include: VisibleFadeEffect
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeAddonsCommonLayout
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeAddonItemsVideos
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeAddonsCommonLayout
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeAddonItemsMusic
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeAddonsCommonLayout
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeAddonItemsPictures
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeAddonsCommonLayout
01:16:56 T:3002718016 WARNING: Skin has invalid include: HomeAddonItemsPrograms
01:16:56 T:3002718016 WARNING: Skin has invalid include: Window_OpenClose_Animation
01:16:56 T:1922366272 WARNING: Previous line repeats 3 times.
01:16:56 T:1922366272  NOTICE: Thread JobWorker start, auto delete: true
01:16:56 T:1922366272   ERROR: GetDirectory - Error getting include
01:16:58 T:1970273088   ERROR: Previous line repeats 3 times.
01:16:58 T:1970273088  NOTICE: Thread JobWorker start, auto delete: true
01:17:13 T:1880943424  NOTICE: Previous line repeats 2 times.
01:17:13 T:1880943424   ERROR: Traceback (most recent call last):
01:17:13 T:1880943424   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/default.py", line 75, in <module>
01:17:15 T:1880943424   ERROR:     main(__addon_path**)
01:17:15 T:1880943424   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/spotimcgui/**init**.py", line 374, in main
01:17:15 T:1880943424   ERROR:     initially_unload_playlists=False,
01:17:15 T:1880943424   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/spotify/session.py", line 309, in **init**
01:17:15 T:1880943424   ERROR:     config = _session.config(*args)
01:17:15 T:1880943424   ERROR: TypeError: incompatible types, LP_callbacks instance instead of LP_callbacks instance
01:17:33 T:3002718016  NOTICE: Storing total System Uptime
01:17:33 T:3002718016  NOTICE: Saving settings
01:17:33 T:3002718016  NOTICE: stop all

..and from here some reboot messages.

**Comment by mazkolain-zz** [comment]
Hi,

It's a strange issue, since I've tried with the 20140126 nightly build and everything loads fine.

Looks like some files on your setup are corrupt (or at least Spotimc is unable to read them). Could you please send me a pastebin of  /home/xbmc/.xbmc/addons/skin.confluence/720p/includes.xml?

Thanks for reporting!

**Comment by olehj** [comment]
http://pastebin.com/5xeCzwiu

**Comment by mazkolain-zz** [comment]
Thanks for the requested file!

Sadly there's nothing wrong with it, so we'll have to try with something else:

The fact is that Spotimc tries with some quirks in order to install a required custom font, and does this by copying the current skin to the userdata folder (making it writeable), and perhaps something went wrong during that copy...

In order to force Spotimc to repeat that copy operation, close XBMC and take the following steps:
- Rename <userdata>/addons/skin.confluence to whatever you want.
- Start Spotimc again and follow the instructions. It will ask you to restart XBMC once more.

Hopefully this will fix the issue you where having...

**Comment by olehj** [comment]
Did what you said.

I needed to reboot after renaming skin.confluence, and after that started spotimc without any problem (no need to reboot either).

Thanks.

**Comment by mazkolain-zz** [comment]
Good to hear that it's fixed now.

Hopefully future releases won't need this quirk, but in the meantime we'll have to deal with the issues it causes.

Regards,
