### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by kylerphillips** [mazkolain-zz/spotimc#157]
Hi guys, 

Getting the following message when trying to run spotimc?

"[Errno 1] Operation not permitted: '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kod" 

error on Amazon Fire TV? Running Kodi

Any ideas?

Thanks

Kyler

**Comment by comio** [comment]
Same here on rikomagic mk902ii box (20141227 android 4,4,2 firmware). 
Any idea?

**Comment by kylerphillips** [comment]
Yep, still experiencing this issue on Amazon Fire TV, Kodi Isengard 15.0 Beta, Software Version: 51.1.5.3_user_515040320
