### ISSUE TITLE
All tracks play for 8 to 10s

### ISSUE THREAD

**Issue by mazkolain-zz** [mazkolain-zz/spotimc#21]
Probably some addons/services query tracks in the background (to gather info about the next tracks and so on).

It may be fixed by implementing the HEAD method in the track streamer proxy, hoping that these services query info about the next tracks using this method.

**Comment by adrianduke** [comment]
+1 getting the same issue on XBMCLive Eden install

**Comment by mazkolain-zz** [comment]
Closing this issue as it has been fixed on the pyspotify-ctypes-proxy repo.
