### ISSUE TITLE
Donation Option

### ISSUE THREAD

**Issue by flofis** [mazkolain-zz/spotimc#25]
HI, 
Considering spotimc is in alpha, it works great.
Please consider adding a donation option (Pledgie or whatever).

Thanks.

**Comment by mazkolain-zz** [comment]
Well, it has some annoying bugs (even chrashes here and there). The fact is that I initially decided to not to add such option, but thinking better, if some day gets stable enough I may reconsider my decision.

Thank you for your support!

**Comment by flofis** [comment]
Well in that case all I can offer is a thumbs up ;)
