### ISSUE TITLE
Minimizing (Closing without stopping music)

### ISSUE THREAD

**Issue by Prahlis** [mazkolain-zz/spotimc#28]
Woulld be great if we could continue browsing XBMC while having it playing in the background. Now the music ends if you leave the app.

**Comment by gobba** [comment]
+1

**Comment by robmeer** [comment]
+1

**Comment by Skyler89** [comment]
+1
I have a little (not really satisfying) workaround: When listening to spotimc, go to the visualization (make sure you have a way to "get home" from there ->keymap.xml) and go to the home screen. You can browse XBMC. Unfortunately spotimc won't open again (until you restart xmbc).

**Comment by monquixote** [comment]
+1 for this issue

**Comment by bobslee** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by mazkolain-zz** [comment]
The last commit completes all the work done on previous months. Closing.
