### ISSUE TITLE
Script error in eden on ubuntu

### ISSUE THREAD

**Issue by xterms** [mazkolain-zz/spotimc#30]
Did a default installation on ubuntu 12.04 / XBMC Eden
Then imported the spotimc zip file according to readme file. 

Then browsed to audio plugins where I get a script error. Nothing happens after this... 

here are xbmc.log entries

----- 8< -----
 15:18:19 T:11104576  NOTICE: Running the application...
15:18:19 T:11104576  NOTICE: ES: Starting event server
15:18:19 T:11104576  NOTICE: starting zeroconf publishing
15:18:19 T:3030371136  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
15:18:19 T:3030371136  NOTICE: UDP: Listening on port 9777
15:18:19 T:2933906240  NOTICE: -->Python Interpreter Initialized<--
15:18:21 T:51305280 WARNING: FillBuffer: curl failed with code 28
15:18:21 T:51305280   ERROR: CFileCurl::CReadState::Open, didn't get any data from stream.
15:18:23 T:51305280 WARNING: FillBuffer: curl failed with code 7
15:18:23 T:51305280   ERROR: CFileCurl::CReadState::Open, didn't get any data from stream.
15:18:44 T:11104576   ERROR: Texture manager unable to load file: /home/fredrik/Desktop/mazkolain-spotimc-0.1-alpha5-6-g2a2905d.zip/icon.png
15:18:58 T:2904546112  NOTICE: -->Python Interpreter Initialized<--
15:18:59 T:2904546112   ERROR: Error Type: <type 'exceptions.ImportError'>
15:18:59 T:2904546112   ERROR: Error Contents: No module named skinutils
15:18:59 T:2904546112   ERROR: Traceback (most recent call last):
                                              File "/home/fredrik/.xbmc/addons/mazkolain-spotimc-2a2905d/default.py", line 47, in <module>
                                                from skinutils import reload_skin
                                            ImportError: No module named skinutils
15:19:33 T:11104576  NOTICE: Storing total System Uptime
15:19:33 T:11104576  NOTICE: Saving settings
15:19:33 T:11104576  NOTICE: stop all

**Comment by mazkolain-zz** [comment]
Hi xterms,

You probably got the package from the upper part links of the download page. Packages generated by these links are invalid because they don't include all the binary dependencies (spotify libs, python eggs, ...).

The valid ones are the zip files located on the lower part of the download page, under the "Download Packages" section.
