### ISSUE TITLE
only logs in first time

### ISSUE THREAD

**Issue by lexter99** [mazkolain-zz/spotimc#39]
On beta 5 I can log into my account. And I set to remember the password but the next time I try to log in it hasn't remembered the password and when I type my details again it just hangs at the login point.
To get past this I have to exit xbmc then restart it and when I type my details again it works. As soon as I exit and try to get back in it does the same.
Eden 11.0 on Ubuntu

**Comment by mazkolain-zz** [comment]
Hi @lexter99,

This issue is closely related to #22, which was fixed on the beta1 release.
