### ISSUE TITLE
Update to v12 of the libspotify api

### ISSUE THREAD

**Issue by mazkolain-zz** [mazkolain-zz/spotimc#45]
It has been a while since the current api version in use (v10) was released. Would be nice to update it to the latest release.

**Comment by suprnova32** [comment]
Yes, it would be nice. I will take a look and see what I can do. Don't expect anything soon, though.

**Comment by mazkolain-zz** [comment]
This issue is almost complete, and remains open until I finish testing all the changes made.

Anyway, thanks for the support!

**Comment by suprnova32** [comment]
Cool @mazkolain thanks for keeping us updated!
