### ISSUE TITLE
Make spotimc run in background

### ISSUE THREAD

**Issue by chrstnwhlrt** [mazkolain-zz/spotimc#58]
Would be grate if the XBMC mainscreen would be reachable and the spotimc stays running in the background.

**Comment by borte** [comment]
+1

**Comment by janderholm** [comment]
Actually it is kind of reachable. By using e.g. the android remote it's possible to navigate to movies, pictures etc. Also managed to get to the mainscreen somehow (at least using aeon nox theme). 

So it should absolutely be possible. But xbmc crashes every few songs though.

**Comment by chrstnwhlrt** [comment]
I read somewhere in the forums that this would require a complete rework of the UI, I like the UI and could agree with it.. therefore → closed.
