### ISSUE TITLE
Script failed

### ISSUE THREAD

**Issue by christianp82** [mazkolain-zz/spotimc#59]
Get 'Script failed' when trying to launch the script.

**OS**: OpenELEC 2.0 Beta 7
**XBMC**: 11.0 GIT:14FEB09
**Spotimc**: 1.0 Beta 1
**Log**:
18:12:39 T:2932865856  NOTICE: Thread XBPyThread start, auto delete: false
18:12:39 T:2932865856  NOTICE: -->Python Interpreter Initialized<--
18:12:40 T:2932865856   ERROR: Error Type: <type 'exceptions.IOError'>
18:12:40 T:2932865856   ERROR: Error Contents: (10, 'No child processes')
18:12:40 T:2932865856   ERROR: Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/script.audio.spotimc/default.py", line 37, in <module>
                                                envutils.set_library_path(dll_dir)
                                              File "/storage/.xbmc/addons/script.audio.spotimc/envutils.py", line 50, in set_library_path
                                                full_path = os.path.join(os.path.abspath(root), get_platform_path())
                                              File "/storage/.xbmc/addons/script.audio.spotimc/envutils.py", line 37, in get_platform_path
                                                if platform.uname()[4] == 'armv6l':
                                              File "./Lib/platform.py", line 1250, in uname
                                              File "./Lib/platform.py", line 1007, in _syscmd_uname
                                            IOError: (10, 'No child processes')

**Comment by mazkolain-zz** [comment]
Are you on raspberry pi or Linux x86?

If it's the latter one then it's a new issue.

**Comment by christianp82** [comment]
I'm on Linux x86 more precise OpenELEC 2.0 Beta 7 (1.95.7) i386 Generic Build

**Comment by brazier** [comment]
there is something wrong with the following.

**~/.xbmc/addons/script.audio.spotimc/envutils.py**

```
if arch == 32:
     if platform.uname()[4] == 'armv6l':
          return 'linux/armv6'
     return 'linux/x86'
```

removing/commenting out the folowing, fixes the issue on my setup, see if it does so in your case, remember to back it up if you chose to remove

```
     if platform.uname()[4] == 'armv6l':
          return 'linux/armv6'
```

its not important, since you know you are running x86.

**Comment by christianp82** [comment]
Removing

```
 if platform.uname()[4] == 'armv6l':
      return 'linux/armv6'
```

solved it, thanks.

**Comment by MartinWallgren** [comment]
I got the same issue on XBMCbuntu. The above suggestion fixed it for me as well

**Comment by mattsches** [comment]
Same here, the solution works for me (running x86).

**Comment by mazkolain-zz** [comment]
Closing it as fixed. The fix will be included on the next beta.

Sorry for the inconveniences this one caused...
