### ISSUE TITLE
Failure to play any track

### ISSUE THREAD

**Issue by newphreak** [mazkolain-zz/spotimc#61]
I cannot play any tracks with the current mainline xbmc of frodo, it seems curl fails to open the tracks.
http://sprunge.us/cFOP

**Comment by mazkolain-zz** [comment]
Regarding the curl error report that appears on the logs (#28), it seems that it's a timeout issue. Are you able to see any album covers? These are also served from the same service.

**Comment by newphreak** [comment]
Yes, all covers are working just fine.

**Comment by newphreak** [comment]
Still times out with beta2.
http://sprunge.us/EQZg
And to show that covers work here is some screenshots taken when creating the log:
http://i.imgur.com/1ThAT.jpg
http://i.imgur.com/9qgMS.png
http://i.imgur.com/PlAXO.png

**Comment by mazkolain-zz** [comment]
Just a brief update on this issue.

I have some clues and believe that it's related to some pull request that was merged recently to the main XBMC branch. 

If my assumptions are correct, there's no chance for Spotimc to provide a fix for this. I've created a thread on the XBMC development forums with all the information I could gather:
http://forum.xbmc.org/showthread.php?tid=142303

**Comment by newphreak** [comment]
Thanks for the update. I will try contacting the appropriate developers.

**Comment by mazkolain-zz** [comment]
Hello,

Closing this issue. It was fixed on the XBMC master branch:
https://github.com/xbmc/xbmc/commit/c61c546b4feedba1be52dc4b0f664d967f275d8b
