### ISSUE TITLE
TypeError: argument "defaultRes" for method "XBMCAddon::xbmcgui::WindowXMLDialog" must be unicode or str

### ISSUE THREAD

**Issue by larseknu** [mazkolain-zz/spotimc#65]
The loading screen starts, then it fails and XBMC shows the error message:
_Script failed! script.spotimc.audio_

**OS:** Windows 8 x64 and Windows 7 x86
**XBMC:** XBMC 20121001 79e7c0c
**Spotimc:** 1.0 Beta 2
**Pastebin:** http://pastebin.com/G7Fks3cR

**Comment by larseknu** [comment]
It's because of Frodo, it runs just fine in Eden. :)

**Comment by jammied** [comment]
I have eden with Windows 7 x86 and I get this error...why?

**Comment by thisismyname** [comment]
I get the same Error on Eden. It works with Alpha 1 to 4 an Beta 1.

Using Ubuntu 12.04 LTS on x64 ION Platform. If you need any Debuginfos, just tell and I'll try to get them.

**Comment by thefifthwit** [comment]
Okay, so I have installed both Beta1 & Beta2 and neither work and I get this exact error. Is there anyway we can get this fixed? I'm running Eden 11 on an ATV2.

**Comment by mazkolain-zz** [comment]
@jammied, @thisismyname: This error is quite generic and probably the real causes of the issue are different for each one. I'll need the debug logs to find out the real origin of the issue.

@thefifthwit: Please keep in mind that Spotimc it's not yet compatible with ATV2. Support for this platform may come in future releases.

**Comment by thefifthwit** [comment]
Oh man. I'm a sorry. I must have missed that. I'm kind of a noob  at this.

**Comment by mazkolain-zz** [comment]
Hi,

This was fixed in faa46ee6a079b616d230a853d755122466320129, but unfortunately did't make it into beta2.

Will be included on the next release.
