### ISSUE TITLE
Raspberry pi cannot open libspotify.so (dose not exsit)

### ISSUE THREAD

**Issue by wendelit** [mazkolain-zz/spotimc#67]
I get this error when starting spotimc:

Error Contents: /home/pi/.xbmc/addons/script.audio.spotimc/resources/dlls/linux/arm/libspotify.so: cannot open shared object file: No such file or directory

tho the linux/arm/libspotify.so dose exist and the ower is the same as the user running XBMC.

Computer: raspbmc on raspberry pi

**Comment by mazkolain-zz** [comment]
Hi,

This is the same as #48.

Here explains why it doesn't work:
https://github.com/mazkolain/spotimc/issues/48#issuecomment-7817002
