### ISSUE TITLE
Script failed. spotify.LibSpotifyError: Invalid library version

### ISSUE THREAD

**Issue by Svaerke** [mazkolain-zz/spotimc#69]
After installing beta-2 (without errors), I get the "plugin Failed" message. As far as I can tell, this is the relevant bit from the xbmc.log:

Code:
16:03:04 T:2636    INFO: initializing python engine.
16:03:04 T:2636   DEBUG: new python thread created. id=8
16:03:04 T:3408    INFO: -->Python script returned the following error<--
16:03:04 T:3408   ERROR: Error Type: <class 'spotify.LibSpotifyError'>
16:03:04 T:3408   ERROR: Error Contents: Invalid library version
16:03:04 T:3408   ERROR: Traceback (most recent call last):
                                              File "C:\Users\test\AppData\Roaming\XBMC\addons\script.audio.spotimc\default.py", line 76, in <module>
                                                main(**addon_path**)
                                              File "C:\Users\test\AppData\Roaming\XBMC\addons\script.audio.spotimc\resources/libs\spotimcgui__init__.py", line 258, in main
                                                initially_unload_playlists=False,
                                              File "build\bdist.win32\egg\spotify\session.py", line 313, in **init**
                                                spotify.handle_sp_error(err)
                                              File "build\bdist.win32\egg\spotify__init__.py", line 20, in handle_sp_error
                                                raise LibSpotifyError(msg)
                                            LibSpotifyError: Invalid library version
16:03:04 T:3408    INFO: -->End of Python script error report<--
16:03:04 T:5952   DEBUG: Thread XBPyThread start, auto delete: 0

I tried deleting the old (beta-1) directory and reinstalling, but still experience the above error.

Running Eden on Win x64 (AMD E-350 processor).
Beta-1 works perfectly on the same setup.
I checked the script.audio.spotimc\resources\dlls\windows\x86\libspotify.dll, and it exists (no x64 dll, though, but that was the case with Beta-1 as well). Also, the filesize and creation date is consistent with the beta-2 package and today's date.

**Comment by mazkolain-zz** [comment]
Mmm, that's rather a strange issue...

Check if the file at script.audio.spotimc/resources/libs/PyspotifyCtypes.egg matches the one on the beta2 installation package.

The libspotify api version that's going to be used is mandated by that python egg, and a mismatch between the one that is supported by libspotify.dll could explain the issue.

**Comment by Svaerke** [comment]
Thank you for your reply.

The PyspotifyCtypes.egg files do match.

This time, to make sure I didn't keep any old files, I renamed my beta1 installation folder to "script.audio.spotimc_old", started up XBMC, installed the beta2 script again via the XBMC interface, and restarted XBMC to retry. Same results as above.

I then exited XBMC and deleted the new addon-folder and restored the beta1 folder, which made the script work again (though obviously, it is now running the Beta1 again).

**Comment by Thelonedevil** [comment]
I get the exact same error using beta4 and win8 x64

Traceback (most recent call last):
18:35:23 T:6816   ERROR:   File "C:\Users\justin\AppData\Roaming\XBMC\addons\script.audio.spotimc\default.py", line 75, in <module>
18:35:23 T:6816   ERROR:     main(**addon_path**)
18:35:23 T:6816   ERROR:   File "C:\Users\justin\AppData\Roaming\XBMC\addons\script.audio.spotimc\resources/libs\spotimcgui__init__.py", line 374, in main
18:35:23 T:6816   ERROR:     initially_unload_playlists=False,
18:35:23 T:6816   ERROR:   File "C:\Users\justin\AppData\Roaming\XBMC\addons\script.audio.spotimc\resources\libs\PyspotifyCtypes.egg\spotify\session.py", line 313, in **init**
18:35:23 T:6816   ERROR:     spotify.handle_sp_error(err)
18:35:23 T:6816   ERROR:   File "C:\Users\justin\AppData\Roaming\XBMC\addons\script.audio.spotimc\resources\libs\PyspotifyCtypes.egg\spotify__init__.py", line 20, in handle_sp_error
18:35:23 T:6816   ERROR:     raise LibSpotifyError(msg)
18:35:23 T:6816   ERROR: LibSpotifyError: Invalid library version

My first thought was that the Libspotify.dll had gotten corrupted in the download, so I removed the addon and re-downloaded and re-installed it, nothing changed, i then downloaded the latest Libspotify.dll from https://developer.spotify.com/technologies/libspotify/ in the hope that it would fix it, but alas the problem persists. Is there anything else i should try?

**Comment by mazkolain-zz** [comment]
Hi,

Sorry for commenting a year later... I answered this issue once in the forums, but forgot to update the corresponding issue.

This was usually related to conflicts between Spotimc and Spotyxbmc2. The latter one loads a previous version of libspotify, and Spotimc's api is designed to work with api v12. Since a previous version spotify lib is already loaded, it won't load the one (newer) provided by Spotimc.

**The solution:** Use a stock XBMC build instead of one that is patched with all the Spotyxbmc2 stuff.
