### ISSUE TITLE
Scrobble to Last.fm

### ISSUE THREAD

**Issue by LegolasV** [mazkolain-zz/spotimc#71]
Would it be possible to scrobble played tracks to Last.fm from Spotimc?

**Comment by LegolasV** [comment]
I just realised this works through the normal XBMC settings, and, therefore, may be ignored.

**Comment by DmitrySandalov** [comment]
Original plugin from XBMC is broken, this on works with Spotimc:
http://forum.xbmc.org/showthread.php?tid=195597
