### ISSUE TITLE
XBMC album covers on mobile remotes

### ISSUE THREAD

**Issue by chrstnwhlrt** [mazkolain-zz/spotimc#72]
Now with the freshest release of the spotimc beta3, the album covers appear in yatse if you take a look in the playqueue. Outside this view (widget, lockscreen controls) the covers aren't displayed yet. Should be hard to fix this :)

**Comment by mazkolain-zz** [comment]
Hi,

Closing this issue in favor of #55, which is the same but that was closed without sufficient testing.

Thanks for reporting!
