### ISSUE TITLE
Track information (time played/song length) doesn't always update

### ISSUE THREAD

**Issue by newphreak** [mazkolain-zz/spotimc#74]
Time played seems to need interaction/movement in the gui most of the time to update the time played information. So it's not polling properly. But it is somewhat random, sometimes it might work well for a few tracks, then stop.

http://sprunge.us/gJcJ

**Comment by mazkolain-zz** [comment]
Hi,

I was able to reproduce this by setting algorithmdirtyregions to 1 in advancedsettings.xml, but looking at the log file you provided this does not seem to be enabled. Perhaps is the default setting on recent Frodo nighties?

Anyway, there's something wrong with this control (the scrollbar next to it is affected too), and could be related to some   issue with the layout xml that prevents it from being tracked. Will keep investigating...

Thanks for the report!

**Comment by newphreak** [comment]
This is back with xbmc frodo rc2

**Comment by mazkolain-zz** [comment]
This was fixed by the XBMC team:
http://trac.xbmc.org/ticket/13887

The label issue was fixed on the commit referenced earlier.
