### ISSUE TITLE
Setting the startup view to playlists crashes XBMC during startup

### ISSUE THREAD

**Issue by mazkolain-zz** [mazkolain-zz/spotimc#76]
What the title says. Windows doesn't seem to be affected, and it produces a crash on Linux.

**Comment by Frank-NL** [comment]
Could you try to look into SpotiMC crashing XBMC @ Linux on startup if you set it to startup with Playlists instead of New content?

**Comment by kib** [comment]
@Frank-NL I have not seen this issue yet. Could you elaborate (version of XBMC, type of linux, hardware, version of spotimc) and i'll try to reproduce it this weekend.

**Comment by Frank-NL** [comment]
Ubuntu 12.10 64 bit, XBMC RC3, SpotiMC beta 3. I can provide a crash log when I'm home, which is not at the moment.

**Comment by kib** [comment]
I run Ubuntu 12.04 LTS 32bit, XBMC RC3, SpotiMC beta 3 at home and haven't seen this before but will test.
I understand you can reproduce the issue ? (start successfully with set to New content, change setting, close, start again and produce crash)

**Comment by mazkolain-zz** [comment]
Hi,

Just confirming the issue on both Openelec and Ubuntu.

As mentioned above, the startup view setting seems to trigger the issue. Setting the initial view to playlists seems to cause the issue, regardless cache is enabled or not.

**Comment by kib** [comment]
Ubuntu 12.04 LTS 32bit, running latest GIT version: can change every setting without issues

I tried: Cache off + Playlists, [restart spotimc], Cache off + New stuff, [restart], Cache on + New stuff, [restart], Cache on + Playlists (current setting)

I don't know if it is the last git edits or the 32bit version that makes the difference or something else altogether but it sure is interesting. :)

**Comment by kib** [comment]
You might need to change the ' Windows does not seem to be affected' !

Confirming this issue on Windows 7 x64 on my friends setup running Frodo RC3. I tested it there during the weekend and instantly got the same issues.

**Comment by Frank-NL** [comment]
Do you still need logs now you both can reproduce this?

**Comment by kib** [comment]
More logs always help :)

**Comment by Frank-NL** [comment]
Here's my log: http://pastebin.com/pXSTegBZ
