### ISSUE TITLE
Report Openelec of issues with playlist.add

### ISSUE THREAD

**Issue by mazkolain-zz** [mazkolain-zz/spotimc#79]
Playlist.add with the extra argument of playlist position crashes XBMC. It happens from Openelec 1.99.5+ to 2.0.0.

**Comment by newphreak** [comment]
Is this the same in 3.0 beta2? (Frodo)

**Comment by mazkolain-zz** [comment]
Hi,

You can happily navigate across albums, playlists and searches until you start playback of any track, time when it crash XBMC.

There's a workaround on Spotimc 1.0-beta3 that prevents this from happening, but it seems that it's not enough for every Openelec release.

I've just reported the issue on the Openelec tracker:
https://github.com/OpenELEC/OpenELEC.tv/issues/1550

**Comment by mazkolain-zz** [comment]
Closing this one since it's 2.0.0 is only affected, and 3.0.0 is near the corner.
