### ISSUE TITLE
Spotimc beta 3 crashes Frodo beta 3

### ISSUE THREAD

**Issue by homburg** [mazkolain-zz/spotimc#82]
When I try to start spotimc from XBMC 12 Frodo beta 3, I am presented with the login screen.
When I login, XBMC crashes.

https://gist.github.com/5b0098557b4c9ea59f2c

**Comment by chrstnwhlrt** [comment]
Agreed → RC1 shows the same error... last lines of the crash report:

22:52:13 T:140397435152128  NOTICE: Previous line repeats 3 times.
22:52:13 T:140397435152128  NOTICE: Thread XBPyThread start, auto delete: false
22:52:13 T:140397435152128  NOTICE: -->Python Interpreter Initialized<--
22:52:13 T:140397435152128  NOTICE: /home/christian/.xbmc/addons/skin.confluence/write_test.txt
22:52:13 T:140397435152128   ERROR: /home/christian/.xbmc/addons/script.audio.spotimc/resources/libs/XbmcSkinUtils.egg/skinutils/fonts.py:138: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
22:52:14 T:140397435152128  NOTICE: /home/christian/.xbmc/addons/skin.confluence/write_test.txt
22:52:14 T:140397435152128  NOTICE: install include: /home/christian/.xbmc/addons/script.audio.spotimc/resources/skins/DefaultSkin/720p/includes.xml
22:52:16 T:140399393552256   ERROR: ClearBlock: Trying to clear non existent block /home/christian/.xbmc/addons/script.audio.spotimc

**Comment by kib** [comment]
Fixed by the XBMC team in Frodo RC2
