### ISSUE TITLE
Frodo RC3 crashes when logging in

### ISSUE THREAD

**Issue by Firesphere** [mazkolain-zz/spotimc#86]
After logging in on Frodo RC3, XBMC just crashes.
Error-log says "no talloc stackframe around, leaking memory" and everything is dead in the water.

Full error-log that actually matters:
19:06:31 T:2328884288  NOTICE: /home/xbian/.xbmc/addons/skin-refocusbig-master/write_test.txt
19:06:31 T:2328884288   ERROR: /home/xbian/.xbmc/addons/script.audio.spotimc/resources/libs/XbmcSkinUtils.egg/skinutils/fonts.py:138: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
19:06:34 T:2328884288  NOTICE: /home/xbian/.xbmc/addons/skin-refocusbig-master/write_test.txt
19:06:34 T:2328884288  NOTICE: install include: /home/xbian/.xbmc/addons/script.audio.spotimc/resources/skins/DefaultSkin/720p/includes.xml
19:06:51 T:3042402304   ERROR: ClearBlock: Trying to clear non existent block /home/xbian/.xbmc/addons/script.audio.spotimc

**Comment by mazkolain-zz** [comment]
Hello,

Does this happen when you have the "New Stuff" view as the default startup one.

There's a known issue that causes a crash on startup if "Playlists" is set as default, which happens since recent XBMC release candidates.

**Comment by elbugs** [comment]
Same issue here!

**Comment by Firesphere** [comment]
I have not been able to get passed the login-screen. It just crashes XBMC when I hit the login-button.
So, I guess it's probably at the new-stuff view.
I don't have any settings.xml (or whatever it's named in spotibmc), if you have an example-settings, I might try and add that one (with my own credentials ofcourse) to the plugin, see if it works?

**Comment by mazkolain-zz** [comment]
You can check this setting from outside Spotimc. On the music addon list with Spotimc selected, just bring up the context menu ("c" key or right mouse click), and you will see this setting on the "Miscellaneous" tab.

If "Playlists" is selected, this issue is probably related to #76.

**Comment by Firesphere** [comment]
Sorry, same issue. Here's the error-log:
`18:21:45 T:3042172928   ERROR: ClearBlock: Trying to clear non existent block /home/xbian/.xbmc/addons/script.audio.spotimc
18:21:55 T:3042172928   ERROR: Previous line repeats 1 times.
18:21:55 T:3042172928 WARNING: Skin has invalid include: screenwidth
18:21:55 T:3042172928 WARNING: Skin has invalid include: transition_OSD2
18:21:55 T:3042172928 WARNING: Skin has invalid include: screenwidth
18:21:55 T:3042172928 WARNING: Skin has invalid include: transition_OSD2
18:21:55 T:3042172928 WARNING: Skin has invalid include: screenwidth
18:21:55 T:3042172928 WARNING: Skin has invalid include: transition_OSD2
18:21:55 T:3042172928 WARNING: Skin has invalid include: screenwidth
18:21:55 T:3042172928 WARNING: Skin has invalid include: transition_OSD2
18:21:55 T:3042172928 WARNING: Skin has invalid include: screenwidth
18:21:55 T:3042172928 WARNING: Skin has invalid include: transition_OSD2
18:21:55 T:3042172928 WARNING: Skin has invalid include: screenwidth
18:21:55 T:3042172928 WARNING: Skin has invalid include: transition_OSD2
18:21:55 T:3042172928 WARNING: Skin has invalid include: screenwidth
18:21:55 T:3042172928 WARNING: Previous line repeats 5 times.
18:21:55 T:3042172928 WARNING: Skin has invalid include: control
18:21:55 T:3042172928 WARNING: Skin has invalid include: screenwidth
18:21:55 T:3042172928 WARNING: Skin has invalid include: transition_OSD2
18:21:55 T:3042172928 WARNING: Skin has invalid include: screenwidth
18:21:55 T:3042172928 WARNING: Skin has invalid include: transition_OSD2
18:21:55 T:3042172928   ERROR: ClearBlock: Trying to clear non existent block /home/xbian/.xbmc/addons/script.audio.spotimc
18:23:10 T:2160063552  NOTICE: libspotify log: 17:23:10.734 I [offline_authorizer.cpp:297] Unable to login offline: no such user`

**Comment by mazkolain-zz** [comment]
Closing this issue in favor of #76.
