### ISSUE TITLE
OPENELEC Script failed and now won't install

### ISSUE THREAD

**Issue by boyzie** [mazkolain-zz/spotimc#87]
Had Spotimc working fine for a couple of weeks now.  Today I got a script failed error.  Tried uninstall and reinstall and still got the error.  Uninstalled once again.  Downloaded fresh zip from here and it won't install from zip or repository. Now I get Installation failed.

I'm on OpenELEC 3.0 (RC 1) - 2.99.1

ERROR: Cache - Failed write to file special://home/addons/script.audio.spotimc/resources/dlls/linux/x86_64/libspotify.so
17:46:42 T:2859594848   ERROR: Could not read addon description of script.audio.spotimc

**Comment by mazkolain-zz** [comment]
Hello, sorry for the delayed answer.

If the installation process is unable to write the libspotify library it may be related to a unclean shutdown of Spotimc. It's a strange issue, but have you tried restarting OpenELEC?

**Comment by boyzie** [comment]
Hi, yes I have tried restarting several times.  It still won't install.

**Comment by Ivru** [comment]
Using openelec 3.2.31 works fine. Very nice job, thanks.
