### ISSUE TITLE
Can't login 

### ISSUE THREAD

**Issue by jonashilmersson** [mazkolain-zz/spotimc#90]
Hi,

I've downloaded the 1.0-beta3-zip of Spotimc for XMBC with the fixed libspotify found here:

http://forum.stmlabs.com/showthread.php?tid=921&pid=50586#pid50586

I've installed it on my Raspbmx 12.0-RC2 but can't login to Spotimc, I've tried both with a premium and a free account. I use the "Spotify details" to login, not the Facebook. 

Any tips?

Brgds

Jonas

**Comment by mazkolain-zz** [comment]
Hello,

Does it crash Raspbmc after entering the details or it directly refuses to login with them (invalid credentials error)?

**Comment by jonashilmersson** [comment]
Hi,

It just refuses to login, no crash. I haven’t looked in any log files yet.

Mvh

Jonas

**Comment by mazkolain-zz** [comment]
Does networking work at all? You can check this on System > System Info > Network. Perhaps outgoing connections on your network should be made using a proxy server?

Anyway, the log files will probably give more details on this issue.

**Comment by jonashilmersson** [comment]
Yepp, no problem with networking otherwise. I've updated XMBC to RC3 build 2013-01-05, but no difference other than a snappier XMBC ;-)

**Comment by mazkolain-zz** [comment]
Sounds very strange. I would still like to see the log file produced by this failure.

Thanks for reporting!

**Comment by jonashilmersson** [comment]
I updated Raspbmc to the nightly build of 2013-01-21, and now the login works, haven't checked the logs though.

Brgds

Jonas
