### ISSUE TITLE
xbmc freezes completely when using another device while playing music

### ISSUE THREAD

**Issue by lomtaslipptas** [mazkolain-zz/spotimc#91]
I use the same spotify account on a few devices. That's not the problem, but you can only listen to music on one device. If you start playing music on a second device, the stream on the first device stopps.

But when I hear music with spotimc and than a child of mine starts playing music on their music systems, than spotimc not only stops playing music, but it freezes completely. no way to end spotify and go back to xbmc or something like this.

**Comment by mazkolain-zz** [comment]
This is a known issue for a long time, but thanks for reporting!

On XBMC Eden, it did freeze for a while, but then the playback got stopped and a message was shown indicating what caused this to happen.

Definitely this one needs another spin...
