### ISSUE TITLE
Unavailable track stops playback.

### ISSUE THREAD

**Issue by protyposis** [mazkolain-zz/spotimc#93]
In 1.0-beta3, when I play a playlist which contains songs that aren't available in Spotify but added from a local music collection, playback just stops instead of skipping the unavailable track. When trying to skip manually, problem #92 kicks in :(

**Comment by protyposis** [comment]
I investigated a bit further, it seems like it keeps on requesting the unavailable song in an infinite loop, here's the log excerpt for one request:

20:13:03 T:3100  NOTICE: 10.12.84.100 - - [17/Feb/2013:20:13:03] "HEAD /track/Kool+Savas:Aura:Optimale+Nutzung+Unserer+Ressourcen:218.wav?idx=64 HTTP/1.1" 404 1624 "" "Spotimc/1.0-beta3 (XBMC/12.0 Git:20130127-fb595f2)"
20:13:03 T:3100  NOTICE: .
20:13:03 T:3640  NOTICE: 10.12.84.100 - - [17/Feb/2013:20:13:03] "GET /track/Kool+Savas:Aura:Optimale+Nutzung+Unserer+Ressourcen:218.wav?idx=64 HTTP/1.1" 404 1624 "" "Spotimc/1.0-beta3 (XBMC/12.0 Git:20130127-fb595f2)"
20:13:03 T:3640  NOTICE: .
20:13:03 T:3004 WARNING: XFILE::CCurlFile::CReadState::FillBuffer: curl failed with code 22
20:13:03 T:3004   ERROR: CCurlFile::CReadState::Open, didn't get any data from stream.
20:13:03 T:3004   ERROR: XFILE::CFileCache::Open - failed to open source http://10.12.84.100:8081/track/Kool+Savas:Aura:Optimale+Nutzung+Unserer+Ressourcen:218.wav?idx=64|X-Spotify-Token=**censored**&User-Agent=Spotimc%2F1.0-beta3+%28XBMC%2F12.0+Git%3A20130127-fb595f2%29
20:13:03 T:3004   ERROR: DVDPlayerCodec::Init: Error opening file http://10.12.84.100:8081/track/Kool+Savas:Aura:Optimale+Nutzung+Unserer+Ressourcen:218.wav?idx=64|X-Spotify-Token=**censored**&User-Agent=Spotimc%2F1.0-beta3+%28XBMC%2F12.0+Git%3A20130127-fb595f2%29

**Comment by protyposis** [comment]
Upon further inspection of the sources and learning a little bit of Python, I think this issue has actually already been solved in commit 4decaf8fca. It's a pity though that the issue section of this project doesn't get much love, would have saved me a lot of time ;)

**Comment by mazkolain-zz** [comment]
Hello @colony,

It's true that I have not paid much attention to issues lately. Perhaps I'm just too focused on fixing Frodo compatibility...

Sorry If this caused a waste of time :(

**Comment by protyposis** [comment]
No problem, the issue is fixed and I can finally use your great plugin without worries, that's the most important thing :)

**Comment by mattsches** [comment]
For completeness' sake: I'm getting those curl errors, too.

This might be related to #61 or/and a regression bug on XBMC's side. After updating to OpenElec 2.99.5, playback in spotimc isn't working anymore. It works again after a downgrade to 2.99.4.

**Comment by mazkolain-zz** [comment]
Hello @mattsches,

I've verified this and it's indeed a bug on Spotimc's side, but has nothing to do with this particular issue, so I've created a new one: https://github.com/mazkolain/spotimc/issues/98

Thanks for reporting!

**Comment by mattsches** [comment]
Great, thx!
