### ISSUE TITLE
Gapless and crossfade support

### ISSUE THREAD

**Issue by gtaylormb** [mazkolain-zz/spotimc#97]
Not sure if this is possible with the current libspotify API, but it would be awesome. IMHO they are essential for any media player.

**Comment by mazkolain-zz** [comment]
Hello,

First of all, sorry for the delayed answer.

XBMC itself does support gapless playback (AFAIK on most plaforms), and you can enable crossfade on the XBMC settings. Just check System > Settings > Music > Playback > Crossfade between songs.
